type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

left_wheel: ['left_actuated_wheel_joint']
right_wheel: ['right_actuated_wheel_joint']

wheel_separation: 0.6
wheel_radius: 0.18

enable_odom_tf: true
odom_frame_id: '/odom'

# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

# Top level frame (link) of the robot description
base_frame_id: base_link

# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 0.2   # m/s
    has_acceleration_limits: true
    max_acceleration       : 0.6   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 0.5   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 1.0   # rad/s^2
