# Configuration for DiffController

controllers:
  forklift_drive_controller:
    # control loop rate (Hz)
    rate: 10.0
    # max time (s) between commands before stopping
    timeout: 1.0
    # wheel radius (m)
    wheel_radius: 0.05
    # wheel separation (m)
    wheel_separation: 0.5
    # encoder resolution (ticks/m)
    ticks_meter: 2000.0
    # maximum acceleration (m/s^2)
    accel_limit: 0.1
    # base frame id
    base_frame_id: "base_link"
    # odom frame id
    odom_frame_id: "odom"
    # PID parameters
    Kp: 5
    Kd: 1
    Ki: 0
    Ko: 50
